databases:
  - name: poker_hand_checker
    databaseName: poker_hand_checker
    user: paresh

services:
  - type: web
    name: poker_hand_checker
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: poker_hand_checker
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false